<div class="login container">
    <?php
    $data['notifications']->render();
    ?>
    <div class="login__title">
        <span>User Registration</span>
    </div>
    <form action="/user/register" method="POST" class="form login__form">
        <div class="form__group">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form__input">
        </div>
        <div class="form__group">
            <label for="email">Email</label>
            <input type="email" name="email" id="email" class="form__input">
        </div>
        <div class="form__group">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" class="form__input">
        </div>
        <div class="form__group">
            <label for="password_confirmation">Password Confirmation</label>
            <input type="password" name="password_confirmation" id="password_confirmation" class="form__input">
        </div>
        <div class="form__actions">
            <button class="btn btn--primary">Register</button>
        </div>
    </form>
    <div class="login__footer">
        <span>Have already an account? <a href="/user/login">Login Here</a></span>
    </div>
</div>