<div class="login container d-flex justify-content-center">
    <?php
    $data['notifications']->render();
    ?>
    <div class="w-75">
        <div class="text-center mb-4">
            <h3>User Registration</h3>
        </div>
        <form action="/user/login" method="POST" class="form login__form">
            <div class="row mb-3">
                <label for="name" class="col-sm-2 col-form-label">Name</label>
                <div class="col-sm-10">
                    <input type="text" name="name" id="name" class="form-control">
                </div>
            </div>
            <div class="row mb-3">
                <label for="email" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" name="email" id="email" class="form-control">
                </div>
            </div>
            <div class="row mb-3">
                <label for="password" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" name="password" id="password" class="form-control">
                    </div>
            </div>
            <div class="row mb-3">
                <label for="password_confirmation" class="col-sm-2 col-form-label">Password Confirmation</label>
                <div class="col-sm-10">
                    <input type="password" name="password_confirmation" id="password_confirmation" class="form-control">
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-sm-2">
                </div>
                <div class="col-sm-10 d-flex justify-content-between align-items-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <span>Have already an account? <a href="/user/login">Login Here</a></span>
                </div>
            </div>
        </form>
    </div>
</div>