<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WavePHP</title>

    <link rel="stylesheet" href="/public/assets/css/global.css">
</head>

<body>
    <header>
        <nav>
            <span>Header Section</span>
            <a href="/user/login">User Login</a>
        </nav>
    </header>
    <main>
        <?php $data['routerView']::run(); ?>
    </main>
    <footer>
        <nav>
            <span>Footer Section</span>
        </nav>
    </footer>
</body>

</html>