<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="/public/assets/css/global.css"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>WavePHP</title>
</head>

<body>
    <?php
    $path = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);
    ?>
    <header class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
            <div class="container-fluid">
                <h2 class="navbar-brand">Products</h2>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar" id="navbarNav">
                    <ul class="navbar-nav">
                        <?php if ($data['session']['user']) : ?>
                            <li class="nav-item">
                                <a class="nav-link <?= $path == '/product/add' ? 'active' : 'text-decoration-underline text-primary' ?>" aria-current="page" href="/product/add">Add Product</a>
                            </li>
                            <span class="vr"></span>
                            <li class="nav-item">
                                <a class="nav-link <?= $path == '/product' ? 'active' : 'text-decoration-underline text-primary' ?>" href="/product">Product</a>
                            </li>
                            <span class="vr"></span>
                            <li class="nav-item">
                                <a class="nav-link <?= $path == '/user/account' ? 'active' : 'text-decoration-underline text-primary' ?>" href="/user/account">User Account</a>
                            </li>
                            <span class="vr"></span>
                            <li class="nav-item">
                                <a class="nav-link <?= $path == '/user/logout' ? 'active' : 'text-decoration-underline text-primary' ?>" href="/user/logout">User Logout</a>
                            </li>
                        <?php else : ?>
                            <li class="nav-item">
                                <a class="nav-link <?= $path == '/user/login' ? 'active' : 'text-decoration-underline text-primary' ?>" href="/user/login">User Login</a>
                            </li>
                        <?php endif ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        <?php $data['routerView']::run(); ?>
    </main>
    <footer class="container">
        <nav>
            <span>Footer Section</span>
        </nav>
    </footer>
</body>

</html>