<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <header>
        <nav>
            <span>Navigation here</span>
        </nav>
    </header>
    <main>
        <?php $data['routerView']::run(); ?>
    </main>
    <footer>
        <nav>
            <span>Footer here</span>
        </nav>
    </footer>
</body>

</html>